#baseurl = "http://echorand.me/linux_voice_4/"
baseurl = "http://echorand.me/test_site_hugo/"
languageCode = "en-us"
title = "Today I Learned"
theme = "hyde-x"
#theme = "blackburn"

disqusShortname = "hugo-todayilearned"
googleAnalytics = "UA-77766553-1"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[taxonomies]
tag = "tags"
category = "categories"

[params]
highlight = "zenburn"
home = "Home"
github = "https://github.com/amitsaha"
twitter = "https://twitter.com/echorand"
rss = true
